### ISSUE TITLE
[Bug] SetItemAsync throws Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time.

### ISSUE THREAD

**Issue by tripleacoder** [Blazored/SessionStorage#71]
Sometimes we get this error from our deployed Blazor apps:

Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeAsync[TValue](IJSRuntime jsRuntime, String identifier, CancellationToken cancellationToken, Object[] args)
   at Blazored.SessionStorage.BrowserStorageProvider.GetItemAsync(String key, Nullable`1 cancellationToken)
   at Blazored.SessionStorage.SessionStorageService.GetItemInternalAsync[T](String key)
   at Blazored.SessionStorage.SessionStorageService.RaiseOnChangingAsync(String key, Object data)
   at Blazored.SessionStorage.SessionStorageService.SetItemAsync[T](String key, T data, Nullable`1 cancellationToken)

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server

I searched, but could not find any other issues on Blazored/SessionStorage. However, there are plenty of examples of the same error text in other Blazor contexts.

Should this exception be handled by the caller or is it possible to fix?

**Comment by chrissainty** [comment]
I think this has to do with Blazor Server apps that have lost their connection to the server, even briefly, while attempting to access browser storage. Without the circuit (connection to the server) the app can't do anything. 

At the moment I think this is best handled in caller code as if we do it, we could mask a real issue causing disconnects. This is essentially the default exception in Blazor Server and I think it's to broad to just swallow.
